In [1]:
import torch
import torch.nn as nn

In [2]:
torch.__version__

'2.5.1+cu121'

In [3]:
torch.cuda.is_available()

True

In [4]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])

t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
t.shape

torch.Size([2, 3])

In [8]:
t.dtype

torch.float32

In [10]:
t.device

device(type='cpu')

In [11]:
t.type()

'torch.FloatTensor'

In [13]:
t.dim()

2

In [14]:
t.size()

torch.Size([2, 3])

In [ ]:
t.numel() # число элементов 

6

In [17]:
t = torch.empty(3, 5)
t

tensor([[7.7584e-37, 1.7096e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [18]:
t = torch.ones(3, 4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
t = torch.full((3, 4), 2)
t

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

In [22]:
t = torch.eye(3, 4)
t

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [27]:
torch.randint(1, 3, (3, 4))

tensor([[2, 2, 2, 2],
        [2, 1, 1, 1],
        [2, 1, 1, 1]])

In [28]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [31]:
torch.linspace(0, 100, 9)

tensor([  0.0000,  12.5000,  25.0000,  37.5000,  50.0000,  62.5000,  75.0000,
         87.5000, 100.0000])

In [33]:
x = torch.randint(0, 10, (2, 5))
x

tensor([[9, 7, 2, 2, 4],
        [3, 2, 3, 5, 3]])

In [ ]:
x[0, 0] # tendor

tensor(9)

In [ ]:
x[0, 0].item() #int

9

In [ ]:
#copy

a = x.new_tensor(x)
a = x.clone().detach() # без detach при взятии тензора из сети не обрудятся связи 
a = torch.empty_like(a).copy_(a)
a = torch.tensor(x)
a = x.detach().clone() # так лучше всего

C:\Users\Admin\AppData\Local\Temp\ipykernel_62184\2727716823.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  a = x.new_tensor(x)
C:\Users\Admin\AppData\Local\Temp\ipykernel_62184\2727716823.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(x)


In [84]:
x[0][0] = 9
x

tensor([[9, 7, 2, 2, 4],
        [3, 2, 3, 5, 3]])

In [85]:
a

tensor([[9, 7, 2, 2, 4],
        [3, 2, 3, 5, 3]])

In [ ]:
#не выделил новую память, просто кинул ссылку
xt = x.t()

x[0, 0] = 30

print(x, '\n', xt)

tensor([[30,  7,  2,  2,  4],
        [ 3,  2,  3,  5,  3]]) 
 tensor([[30,  3],
        [ 7,  2],
        [ 2,  3],
        [ 2,  5],
        [ 4,  3]])


In [ ]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[2, 2], [2, 2]])

torch.stack((x, y)) # состыковка

tensor([[[1, 2],
         [3, 4]],

        [[2, 2],
         [2, 2]]])

In [ ]:
torch.unbind(x) #разстыковка 

(tensor([1, 2]), tensor([3, 4]))

In [ ]:
torch.cat((x, y)) # без новой размерности

tensor([[1, 2],
        [3, 4],
        [2, 2],
        [2, 2]])

In [97]:
x.unsqueeze(dim=0).size()

torch.Size([1, 2, 2])

In [99]:
torch.cat((x[None, :, :], y[None, :, :]))

tensor([[[1, 2],
         [3, 4]],

        [[2, 2],
         [2, 2]]])

тензор храниться как строка элементов, так что суммы по срокам быстрее чем по столбцам

но если транспонировать, то это свойство (contiguous) пропадает 


Размер тензром омжно менять при помощи veiw(работает только на contiguous). Реально данные не перемещаются, но для нас они становятся другого размера

Еще есть reshape, работает всегда, если не получается veiw, то копирует данные. 

In [111]:
x.view(-1)

tensor([1, 2, 3, 4])

In [125]:
x.flatten()

tensor([1, 2, 3, 4])

In [113]:
x.t().is_contiguous()

False

In [ ]:
x.storage() # то как реально лежит в памяти

C:\Users\Admin\AppData\Local\Temp\ipykernel_62184\2674773268.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage()


 1
 2
 3
 4
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 4]

In [ ]:
x.stride() # насколько мы должны пройти дальше, чтобы попасть на новую строку

(2, 1)

In [116]:
x.t().stride()

(1, 2)

In [123]:
x.permute(0, 1) # поменять местами размерности

tensor([[1, 3],
        [2, 4]])

In [124]:
x.transpose(0, 1), x.t(), x.t_() # t_ это inplace операция, тоже самое, что x = x.t()

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [ ]:
x @ y, x.mm(y), x.matmul(y), torch.matmul(x, y) #все одно и тоже, почти

In [126]:
v = torch.tensor([1, 2])

In [128]:
x.mv(v) #матрица на вектор

tensor([ 5, 11])

In [ ]:
torch.dot(v, v) #скалярное произведение

tensor(5)