In [1]:
import numpy as np

In [7]:
np.__version__

'1.26.4'

In [9]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Admin/anaconda3/Library/include
    lib directory: C:/Users/Admin/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: 

In [10]:
np.show_runtime()

[{'numpy_version': '1.26.4',
  'python': '3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) '
            '[MSC v.1938 64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='LAPTOP-OSEVL9J0', release='10', version='10.0.19045', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'filepath': 'C:\\Users\\Admin\\anaconda3\\L

In [37]:
z = np.zeros((10, 10), float)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
z.size * z.itemsize

800

In [42]:
np.info(np.argmax)

Returns the indices of the maximum values along an axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    By default, the index is into the flattened array, otherwise
    along the specified axis.
out : array, optional
    If provided, the result will be inserted into this array. It should
    be of the appropriate shape and dtype.
keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the array.

    .. versionadded:: 1.22.0

Returns
-------
index_array : ndarray of ints
    Array of indices into the array. It has the same shape as `a.shape`
    with the dimension along `axis` removed. If `keepdims` is set to True,
    then the size of `axis` will be 1 with the resulting array having same
    shape as `a.shape`.

See Also
--------
ndarray.argmax, argmin
amax : The maximum value along a given axis.
unravel_ind

In [43]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [46]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [63]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [83]:
np.arange(9).reshape(3, -1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [114]:
np.eye(3, 4, 2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [121]:
np.random.randint(0, 3, (3, 3, 3))

array([[[0, 1, 2],
        [1, 1, 1],
        [1, 1, 0]],

       [[1, 1, 0],
        [1, 1, 2],
        [2, 2, 0]],

       [[1, 2, 1],
        [1, 0, 1],
        [1, 1, 0]]])

In [124]:
a = np.random.randint((10, 10))
a.min(), a.max()

(1, 6)

In [134]:
np.set_printoptions(suppress=True, precision=4, linewidth=100)
a = np.random.random(30)
print(a)
a.mean(), a.std()

[0.3149 0.5888 0.4111 0.3148 0.3128 0.5944 0.855  0.3922 0.4398 0.0207 0.7653 0.3901 0.515  0.4198
 0.8676 0.2132 0.2175 0.6679 0.2436 0.2192 0.8332 0.6508 0.5648 0.2378 0.4379 0.6688 0.0799 0.8018
 0.5486 0.0185]


(0.4535323114011504, 0.24045156847176105)

In [138]:
(np.random.random(9)*10).round(0).reshape(3, 3)

array([[8., 0., 4.],
       [6., 4., 9.],
       [7., 5., 8.]])

In [ ]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [167]:
b = np.ones((10, 10))
b[[0, -1], :] = 0
b[:, [0, -1]] = 0
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [173]:
np.info(np.pad)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
    for each axis.
    ``(before, after)`` or ``((before, after),)`` yields same before
    and after pad for each axis.
    ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
    for all axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'media

In [186]:
a = np.random.randint(0, 11, (3, 4))
a = np.pad(a, 2, 'constant', constant_values=0)
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  9,  2,  3,  0,  0],
       [ 0,  0,  9,  9,  3,  3,  0,  0],
       [ 0,  0, 10,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [34]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [46]:
a = 1 + np.arange(4)

A = np.diag(a, -1)
A

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [54]:
a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [56]:
a = np.zeros((8, 8))
a[1::2, 1::2] = 1
a[::2, ::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [61]:
np.unravel_index(99, (6, 7, 8))


(1, 5, 3)

In [75]:
z = np.eye(2, dtype=int)

Z = np.tile(A=z, reps=(4, 4))
Z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [35]:
import numpy as np
a = np.random.random((5, 5))

a = a / np.sum(a, axis=1)[:, None]
a

array([[3.11323943e-01, 2.48084232e-02, 2.30268541e-01, 3.42272452e-01,
        9.13266407e-02],
       [3.75515766e-01, 1.01586267e-02, 3.88455404e-01, 2.25554598e-01,
        3.15605241e-04],
       [3.14211363e-01, 1.64213857e-01, 2.67553533e-01, 2.01082774e-01,
        5.29384730e-02],
       [2.26224969e-01, 2.69055101e-01, 2.81711626e-01, 6.21659773e-02,
        1.60842328e-01],
       [3.78568817e-01, 3.04010888e-01, 8.87706663e-02, 1.90643003e-01,
        3.80066251e-02]])

In [46]:
color = np.dtype([
    ('red', np.uint8),
    ('ared', np.uint8),
    ('bred', np.uint8),
    ('cred', np.uint8),
])
color

dtype([('red', 'u1'), ('ared', 'u1'), ('bred', 'u1'), ('cred', 'u1')])

In [48]:
color['ared']

dtype('uint8')

In [54]:
a = np.ones((5, 3))
b = np.ones((3, 2))


In [55]:
a @ b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
a = np.random.randint(0, 10, 20)
a[(a > 3) & (a < 8)] *= -1
a

array([2, 5, 6, 8, 7, 8, 7, 6, 3, 9, 3, 3, 3, 8, 1, 3, 9, 8, 6, 7])

In [69]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [2]:
z=np.arange(10)
print('Исходный вектор:\n',z, '\n')
print('z**z:\n', z**z, '\n')
print('2 << z >> 2:\n', 2 << z >> 2, '\n')
print('z <- z\n', z <- z, '\n')
print('1j*z\n', 1j*z, '\n')
print('z/1/1', z/1/1, '\n')

Исходный вектор:
 [0 1 2 3 4 5 6 7 8 9] 

z**z:
 [        1         1         4        27       256      3125     46656
    823543  16777216 387420489] 

2 << z >> 2:
 [  0   1   2   4   8  16  32  64 128 256] 

z <- z
 [False False False False False False False False False False] 

1j*z
 [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j] 

z/1/1 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 



In [6]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\Admin\AppData\Local\Temp\ipykernel_24772\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

In [8]:
a = (np.arange(15)-7)/4
a

array([-1.75, -1.5 , -1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,
        0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75])

In [11]:
a.round()

array([-2., -2., -1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.,
        2.,  2.])

In [14]:
np.copysign(np.ceil(np.abs(a)), a)

array([-2., -2., -2., -1., -1., -1., -1.,  0.,  1.,  1.,  1.,  1.,  2.,
        2.,  2.])

In [17]:
np.where(a>0, np.ceil(a), np.floor(a))

array([-2., -2., -2., -1., -1., -1., -1.,  0.,  1.,  1.,  1.,  1.,  2.,
        2.,  2.])

In [20]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

print(a, b)

[2 2 0 9 7 5 3 7 5 2] [4 7 9 8 5 9 2 2 7 6]


In [21]:
np.intersect1d(a, b)

array([2, 5, 7, 9])

In [37]:
deafults = np.seterr(all='ignore')
#Z = np.ones(1) / 0
#Z

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

True

In [47]:
np.datetime64('today') - np.timedelta64(1)

numpy.datetime64('2025-04-20')

In [60]:
np.arange('2016-07', '2023-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', ..., '2023-07-29',
       '2023-07-30', '2023-07-31'], dtype='datetime64[D]')

In [69]:
A = np.ones(3)
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
A

array([-1.5, -1.5, -1.5])

In [73]:
a = np.random.random(10) * 10
a

array([5.12861085, 4.94221522, 4.27128298, 6.57207591, 5.02466218,
       5.46404857, 5.83790598, 1.99628124, 4.5185145 , 8.6221624 ])

In [75]:
np.floor(a)

array([5., 4., 4., 6., 5., 5., 5., 1., 4., 8.])

In [76]:
a.astype(int)

array([5, 4, 4, 6, 5, 5, 5, 1, 4, 8])

In [ ]:
a//1

array([5., 4., 4., 6., 5., 5., 5., 1., 4., 8.])

In [79]:
a - a%1

array([5., 4., 4., 6., 5., 5., 5., 1., 4., 8.])

In [ ]:
#Поэлементно получает число которое ближе к 0, отличается от floor тем, что floor для -1.7 выдаст -2, а этот -1
np.trunc(a)

array([5., 4., 4., 6., 5., 5., 5., 1., 4., 8.])

In [ ]:
a = np.arange(5)
np.tile(a, (5, 1))

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [91]:
a = np.zeros((5, 5))

a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [120]:
def gen():
    for a in range(1090000):
        yield a

t = gen()

np.fromiter(t, dtype=float, count=1090)

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 1.087e+03, 1.088e+03,
       1.089e+03])

In [126]:
a = np.linspace(0, 1, 11, endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [148]:
a = np.random.random(10)
a.sort()
a

array([0.00977591, 0.03353855, 0.08115742, 0.14770662, 0.15179573,
       0.42736152, 0.58786142, 0.61633623, 0.92986453, 0.93779683])

In [ ]:
a = np.random.random(10)
a = np.sort(a)  # Возвращает новый отсортированный массив, не меняя `a`
print(a)

#np.sort(a) можно использовать как хочешь, а вот a.sort() солртирует на месте на создавая копии и возвращяет нан, так что не нужно его присваивать , нгужно просто вызвать a.sort()

[0.10588923 0.22170815 0.29158223 0.3721532  0.38266312 0.40091935
 0.69386469 0.74214026 0.79495207 0.95296071]


In [ ]:
import numpy as np

a = np.random.random(10)
a.sort()

[0.00766131 0.07381263 0.11905093 0.18723745 0.23746358 0.49143441
 0.55447321 0.64611004 0.68163713 0.70083943]


In [1]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np
from timeit import timeit

arr_list = [1, 2, 3, 4, 5]  # Python list
arr_np = np.array(arr_list)  # NumPy array

# Варианты суммирования
def test_sum_list(): 
    arr = list(arr_np)
    return sum(arr)

def test_np_sum(): 
    return np.sum(arr_np)

def test_np_add_reduce(): 
    return np.add.reduce(arr_np)

# Замеряем время (1_000_000 запусков)
print("sum(list):", timeit(test_sum_list, number=1_000_000))
print("np.sum:", timeit(test_np_sum, number=1_000_000))
print("np.add.reduce:", timeit(test_np_add_reduce, number=1_000_000))

sum(list): 2.0322025999776088
np.sum: 4.088381900044624
np.add.reduce: 1.9566532000317238


In [ ]:
a = np.arange(5)
A = np.tile(a, (5, 1))

#Reduces `array`'s dimension by one, by applying ufunc along one axis.
np.add.reduce(A, axis=1)

array([10, 10, 10, 10, 10])

In [16]:
a = np.random.randint(0, 2, 10)
b = np.random.randint(0, 2, 10)

In [25]:
res = (a == b).astype(int)
res = np.multiply.reduce(res).astype(bool)
res

False

In [26]:
np.allclose(a, b)

False

In [27]:
np.array_equal(a, b)

False

In [31]:
c = b
(b == b).all()

True

In [37]:
a = np.random.randint(0, 3, 10)
a

array([2, 1, 1, 1, 1, 2, 0, 0, 2, 1])

In [39]:
a.setflags(write=False)

In [40]:
a[0] == 999
a

array([2, 1, 1, 1, 1, 2, 0, 0, 2, 1])

In [56]:
a = np.random.randint(0, 10, 10)
a

array([4, 0, 9, 2, 8, 9, 1, 1, 6, 8])

In [44]:
max = np.max(a)
a[a == max] = 0
a

array([2, 5, 0, 2, 5, 0, 3, 4, 0, 3])

In [57]:
a[a.argmax()] = 0
a

array([4, 0, 0, 2, 8, 9, 1, 1, 6, 8])

In [52]:
max = np.max(a)
a = np.where(a == max, 0, a)
a

array([6, 0, 0, 2, 6, 3, 8, 2, 4, 0])

In [62]:
N = 4
a = np.arange(N+1) / N
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [64]:
x, y = np.meshgrid(a, a)
x, y

(array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]]))

In [66]:
np.stack((x, y), axis=-1)

array([[[0.  , 0.  ],
        [0.25, 0.  ],
        [0.5 , 0.  ],
        [0.75, 0.  ],
        [1.  , 0.  ]],

       [[0.  , 0.25],
        [0.25, 0.25],
        [0.5 , 0.25],
        [0.75, 0.25],
        [1.  , 0.25]],

       [[0.  , 0.5 ],
        [0.25, 0.5 ],
        [0.5 , 0.5 ],
        [0.75, 0.5 ],
        [1.  , 0.5 ]],

       [[0.  , 0.75],
        [0.25, 0.75],
        [0.5 , 0.75],
        [0.75, 0.75],
        [1.  , 0.75]],

       [[0.  , 1.  ],
        [0.25, 1.  ],
        [0.5 , 1.  ],
        [0.75, 1.  ],
        [1.  , 1.  ]]])

In [68]:
N = 5  # инициируем кол-во частей разбивки области по x и по y 
Z = np.zeros((N,N), [('x',float),('y',float)])  # зададим массив для координат покрытия области со спец типом
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,num=N), np.linspace(0,1,num=N))

Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [70]:
a = np.arange(4)
b = a + 0.5

In [71]:
c = a[:, None] + b
c

array([[0.5, 1.5, 2.5, 3.5],
       [1.5, 2.5, 3.5, 4.5],
       [2.5, 3.5, 4.5, 5.5],
       [3.5, 4.5, 5.5, 6.5]])

In [72]:
a_g, b_g = np.meshgrid(a, b, indexing='ij')
a_g, b_g

(array([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]),
 array([[0.5, 1.5, 2.5, 3.5],
        [0.5, 1.5, 2.5, 3.5],
        [0.5, 1.5, 2.5, 3.5],
        [0.5, 1.5, 2.5, 3.5]]))

In [73]:
d = 1 / (a_g - b_g)
d

array([[-2.        , -0.66666667, -0.4       , -0.28571429],
       [ 2.        , -2.        , -0.66666667, -0.4       ],
       [ 0.66666667,  2.        , -2.        , -0.66666667],
       [ 0.4       ,  0.66666667,  2.        , -2.        ]])

In [74]:
np.linalg.det(d)

44.384169312169305

In [ ]:
e = 1 / 

In [80]:
np.subtract.outer(a, b)

array([[-0.5, -1.5, -2.5, -3.5],
       [ 0.5, -0.5, -1.5, -2.5],
       [ 1.5,  0.5, -0.5, -1.5],
       [ 2.5,  1.5,  0.5, -0.5]])

In [91]:
for t in [np.int8, np.int32, np.int64, np.uint64]:
    print(t.__name__, np.iinfo(t).min, np.iinfo(t).max)

int8 -128 127
int32 -2147483648 2147483647
int64 -9223372036854775808 9223372036854775807
uint64 0 18446744073709551615


In [92]:
a

array([0, 1, 2, 3])

In [106]:
a = np.random.randint(0, 100, (100, 14))
a

array([[78, 65, 44, 29, 90, 20, 13, 18, 14, 91, 10, 93, 21, 33],
       [23, 66, 54, 14, 61, 76, 66, 55, 73, 79, 11, 98, 72, 11],
       [16, 15, 32,  4, 40, 46,  9, 75, 88,  1, 48, 87, 23, 68],
       [29, 25, 11, 24, 99, 58, 36, 23, 42, 28, 23, 80, 63, 29],
       [80, 27, 95, 58, 25, 59,  1, 17, 94, 43, 11, 18, 47, 43],
       [41, 47, 80, 16, 42, 87, 73, 21, 98, 29, 29, 19, 17,  2],
       [84, 55, 48,  9, 75, 37, 73, 45, 97, 21, 13,  7, 48, 21],
       [31, 78, 68, 75, 74, 52, 42, 16, 36, 19, 52, 43,  6, 24],
       [31, 68, 15,  9, 49, 43, 65, 53, 44, 29, 59, 22, 60, 17],
       [47, 98, 45, 74, 83, 41,  5, 91, 77, 44, 51, 16, 49, 13],
       [23, 42, 85, 26, 96,  0, 38, 63, 29, 15, 25, 62, 97, 77],
       [34, 20, 46, 22, 60, 57, 17, 69,  7, 10, 14, 62, 11, 64],
       [12, 59, 52,  0, 19, 24, 87, 74, 90, 49, 35,  3, 41,  1],
       [39, 82, 52, 72, 43, 62, 80, 26, 84, 99, 38, 84, 11, 10],
       [87, 83, 34, 32,  1, 47, 71, 12,  2, 92, 10, 22, 28, 39],
       [72, 57, 91,  9, 2

In [ ]:
with np.printoptions(threshold=np.inf):  # threshold=float("inf") тоже работает
    print(a)

print('------')
print(a)  # Вернётся к стандартным настройкам

In [108]:
a = np.random.randint(-10, 10, 10)
a

array([ -9,   3,   4,  -8, -10,   7,   5,  -9,  -4,   4])

In [109]:
b = 5.5

In [114]:
a[np.argmin(np.abs(a - b))]

5

In [2]:
import numpy as np

In [3]:
N = 10  # размер вектора

Z = np.ones(N)
print(f'Исходный вектор Z единичных значений длиной {N}:\n{Z}\nСумма элементов вектора Z: {sum(Z)}')
I = np.random.randint(1,N-1,N*2)
print(f'Вектор индексов I длиной {2*N} из случайных значений равномерно распределенных на полуинтервале [0,{N}):\n', I)
Z += np.bincount(I, minlength=len(Z))
print(f'Преобразованный вектор Z_:\n{Z}\nСумма элементов вектора Z_: {sum(Z)}')
print('Проверка выражения np.sum(Z_) = np.sum(Z) + len(I): ', np.sum(Z) == N + len(I))

Исходный вектор Z единичных значений длиной 10:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Сумма элементов вектора Z: 10.0
Вектор индексов I длиной 20 из случайных значений равномерно распределенных на полуинтервале [0,10):
 [8 3 5 8 3 3 3 3 5 7 6 1 7 3 4 4 8 2 1 4]
Преобразованный вектор Z_:
[1. 3. 2. 7. 4. 3. 2. 3. 4. 1.]
Сумма элементов вектора Z_: 30.0
Проверка выражения np.sum(Z_) = np.sum(Z) + len(I):  True
